services:
  spring-security-example:
    build: .
    container_name: spring-security-example
    ports:
      - "8080:8080"
    volumes:
      - ./springsecurityexample:/home/springsecurityexample

  db:
    image: mariadb:lts
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=instagram_db
      - MARIADB_USER=instagram_user
      - MARIADB_PASSWORD=instagram_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local

